# Generated by Django 2.1.2 on 2018-10-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zone_text',
            field=models.TextField(blank=True, verbose_name='Text zone view'),
        ),
    ]
