# Generated by Django 2.1.2 on 2018-10-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20181026_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zone_text',
            field=models.BinaryField(blank=True, verbose_name='Text zone view'),
        ),
    ]
